  - label: ":ios::detox: RN .71 + iOS: Tests app"
    command:
      - "ping 46.101.117.193"
    env:
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      REACT_NATIVE_VERSION: 0.71.10
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/**/allure-report-*.html"
      - "/Users/builder/work/artifacts*.tar.gz"
